//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceRequestForm
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> AdvanceTypeID { get; set; }
        public string Description { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> AdvanceDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPassive { get; set; }
    
        public virtual AdvanceType AdvanceType { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
