//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorizations
    {
        public int ID { get; set; }
        public int ModuleId { get; set; }
        public int PageID { get; set; }
        public int UserID { get; set; }
        public bool IsRead { get; set; }
        public bool IsCreate { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public int UpdateUserID { get; set; }
        public Nullable<bool> IsPassive { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual Pages Pages { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
