//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchRole
    {
        public int ID { get; set; }
        public int SystemUserID { get; set; }
        public int BrancID { get; set; }
        public bool IsRead { get; set; }
        public bool IsCreat { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public int UpdateUserID { get; set; }
        public Nullable<bool> IsPassive { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
