//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactionValueMap
    {
        public int Id { get; set; }
        public Nullable<int> InventoryTransactionId { get; set; }
        public Nullable<int> ValueId { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual InventoryTransactions InventoryTransactions { get; set; }
        public virtual Value Value { get; set; }
    }
}
