//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryTransactions()
        {
            this.InventoryTransactionValueMap = new HashSet<InventoryTransactionValueMap>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SystemUserID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> WhichGroup { get; set; }
        public string InIp { get; set; }
        public string OutIp { get; set; }
        public string TopIp { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string InvoiceNo { get; set; }
        public string InventoryCode { get; set; }
        public string InventoryName { get; set; }
        public string UniversalIdentity { get; set; }
        public string OtherPrograms { get; set; }
        public string InventoryMacAddress { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateDateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual WhichGroup WhichGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransactionValueMap> InventoryTransactionValueMap { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
