//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRequestForm
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> PermissionTypeID { get; set; }
        public Nullable<int> PermissionStatusID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual PermissionStatus PermissionStatus { get; set; }
        public virtual PermissionType PermissionType { get; set; }
    }
}
