//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUser()
        {
            this.Authorizations = new HashSet<Authorizations>();
            this.InventoryTransactions = new HashSet<InventoryTransactions>();
            this.SeniorDepartment = new HashSet<SeniorDepartment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public Nullable<int> WhichGroupUserID { get; set; }
        public Nullable<int> PermissionNo { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> JopStartDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authorizations> Authorizations { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryTransactions> InventoryTransactions { get; set; }
        public virtual WhichGroup WhichGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeniorDepartment> SeniorDepartment { get; set; }
    }
}
